import ProductImage from "@/assets/products-1-min.jpg";
import ProductImage2 from "@/assets/products-4-min-300x345.jpg";
import ProductImage3 from "@/assets/products-9-min-300x345.jpg";

export const Data = [
    {
        id: 1,
        title: "Digital Cameras",
        imageUrl: ProductImage,
        price: 100,
        discount: 20,
        rating: 1,
        stock: 10,
    },
    {
        id: 2,
        title: "Headphones",
        imageUrl: ProductImage2,
        price: 50,
        discount: 10,
        rating: 4,
        stock: 10,
    },
    {
        id: 3,
        title: "Smart Watches",
        imageUrl: ProductImage3,
        price: 200,
        rating: 4,
        stock: 10,
    },
    {
        id: 4,
        title: "Portable Audio",
        imageUrl: ProductImage,
        price: 150,
        rating: 5,
        stock: 0,
    },
    {
        id: 5,
        title: "Portable Audio",
        imageUrl: ProductImage3,
        price: 150,
        rating: 1,
        stock: 10,
    },
    {
        id: 6,
        title: "Portable Audio",
        imageUrl: ProductImage2,
        price: 150,
        discount: 20,
        rating: 4,
        stock: 10,
    },
    {
        id: 7,
        title: "Portable Audio",
        imageUrl: ProductImage,
        price: 150,
        rating: 2,
        stock: 10,
    },
    {
        id: 8,
        title: "Portable Audio",
        imageUrl: ProductImage2,
        price: 150,
        rating: 4,
        stock: 10,
    },
    {
        id: 9,
        title: "Portable Audio",
        imageUrl: ProductImage3,
        price: 150,
        rating: 4,
        stock: 10,
    },
    {
        id: 10,
        title: "Portable Audio",
        imageUrl: ProductImage2,
        price: 150,
        rating: 3,
        stock: 10,
    },
    {
        id: 11,
        title: "Digital Cameras",
        imageUrl: ProductImage,
        price: 100,
        discount: 20,
        rating: 1,
        stock: 10,
    },
    {
        id: 12,
        title: "Headphones",
        imageUrl: ProductImage2,
        price: 50,
        discount: 10,
        rating: 4,
        stock: 10,
    },
    {
        id: 13,
        title: "Smart Watches",
        imageUrl: ProductImage,
        price: 200,
        rating: 4,
        stock: 10,
    },
    {
        id: 14,
        title: "Portable Audio",
        imageUrl: ProductImage3,
        price: 150,
        rating: 5,
        stock: 0,
    },
    {
        id: 15,
        title: "Portable Audio",
        imageUrl: ProductImage2,
        price: 150,
        rating: 1,
        stock: 10,
    },
    {
        id: 16,
        title: "Portable Audio",
        imageUrl: ProductImage,
        price: 150,
        discount: 20,
        rating: 4,
        stock: 10,
    },
    {
        id: 17,
        title: "Portable Audio",
        imageUrl: ProductImage3,
        price: 150,
        rating: 2,
        stock: 10,
    },
    {
        id: 18,
        title: "Portable Audio",
        imageUrl: ProductImage2,
        price: 150,
        rating: 4,
        stock: 10,
    },
    {
        id: 19,
        title: "Portable Audio",
        imageUrl: ProductImage,
        price: 150,
        rating: 4,
        stock: 10,
    },
    {
        id: 20,
        title: "Portable Audio",
        imageUrl: ProductImage,
        price: 150,
        rating: 3,
        stock: 10,
    },
];
